# Generated by Django 3.2.8 on 2021-10-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='cost',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
